In [1]:
import numpy as np
numbers = np.array(range(1, 11), copy=True)

In [2]:
ones = np.ones([2, 4], dtype=np.float64)
zeros = np.zeros([2, 4], dtype=np.float64)
empty = np.empty([2, 4], dtype=np.float64)

In [3]:
ones.shape

(2, 4)

In [4]:
numbers.ndim

1

In [6]:
zeros.dtype

dtype('float64')

In [9]:
eye = np.eye(3, k=0)
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
eye

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [12]:
np_numbers = np.arange(2, 5, 0.25)
np_inumbers = np_numbers.astype(np.int)
np_inumbers

array([2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

## Transposing and Reshaping

In [14]:
sap = np.array(["MMM", "ABT", "ABBV", "ACN", "ACE", "ATVI", "ADBE", "ADT"])
sap

array(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ATVI', 'ADBE', 'ADT'],
      dtype='<U4')

In [15]:
sap2d = sap.reshape(2, 4)
sap2d

array([['MMM', 'ABT', 'ABBV', 'ACN'],
       ['ACE', 'ATVI', 'ADBE', 'ADT']], dtype='<U4')

In [16]:
sap3d = sap.reshape(2, 2, 2)
sap3d

array([[['MMM', 'ABT'],
        ['ABBV', 'ACN']],

       [['ACE', 'ATVI'],
        ['ADBE', 'ADT']]], dtype='<U4')

In [17]:
sap2d.T

array([['MMM', 'ACE'],
       ['ABT', 'ATVI'],
       ['ABBV', 'ADBE'],
       ['ACN', 'ADT']], dtype='<U4')

In [18]:
sap3d.swapaxes(1, 2)

array([[['MMM', 'ABBV'],
        ['ABT', 'ACN']],

       [['ACE', 'ADBE'],
        ['ATVI', 'ADT']]], dtype='<U4')

In [19]:
sap3d.transpose((0, 2, 1))

array([[['MMM', 'ABBV'],
        ['ABT', 'ACN']],

       [['ACE', 'ADBE'],
        ['ATVI', 'ADT']]], dtype='<U4')

## Indexing and Slicing

In [21]:
dirty = np.array([9, 4, 1, -0.01, -0.02, -0.001])
whos_dirty = dirty < 0 # Boolean array, to be used as Boolean index
whos_dirty

array([False, False, False,  True,  True,  True])

In [22]:
dirty[whos_dirty] = 0 # Change all negative values to 0
dirty

array([9., 4., 1., 0., 0., 0.])

In [23]:
linear = np.arange(-1, 1.1, 0.2)
(linear <= 0.5) & (linear >= -0.5)

array([False, False, False,  True,  True,  True,  True,  True, False,
       False, False])

In [24]:
sap[[1, 2, -1]]

array(['ABT', 'ABBV', 'ADT'], dtype='<U4')

In [25]:
sap2d[:, [1]]

array([['ABT'],
       ['ATVI']], dtype='<U4')

In [26]:
sap2d[:, 1]

array(['ABT', 'ATVI'], dtype='<U4')

## Broadcasting

In [31]:
a = np.arange(4)
b = np.arange(1, 5) 
a+b

array([1, 3, 5, 7])

In [32]:
a * 5

array([ 0,  5, 10, 15])

In [34]:
noise = np.eye(4) + 0.01 * np.ones((4, ))
noise

array([[1.01, 0.01, 0.01, 0.01],
       [0.01, 1.01, 0.01, 0.01],
       [0.01, 0.01, 1.01, 0.01],
       [0.01, 0.01, 0.01, 1.01]])

In [39]:
noise = np.eye(4) + 0.01 * np.random.random([4, 4])
noise

array([[1.00892691e+00, 9.97342018e-03, 9.03259349e-03, 9.32030943e-03],
       [3.68127526e-03, 1.00512133e+00, 9.50703848e-03, 4.19162897e-03],
       [8.93983004e-03, 7.30410825e-03, 1.00967585e+00, 3.99722939e-03],
       [8.54283982e-03, 1.03958983e-03, 9.81893755e-04, 1.00537689e+00]])

In [40]:
   np.round(noise, 2)

array([[1.01, 0.01, 0.01, 0.01],
       [0.  , 1.01, 0.01, 0.  ],
       [0.01, 0.01, 1.01, 0.  ],
       [0.01, 0.  , 0.  , 1.01]])

## Demystifying Universal Functions

In [47]:
stocks = np.array([ 140.49,    0.97,   40.68,   41.53,   55.7 ,   57.21,   98.2 ,
         99.19,  109.96,  111.47,   35.71,   36.27,   87.85,   89.11,
         30.22,   30.91])

In [48]:
stocks = stocks.reshape(8, 2).T
stocks

array([[140.49,  40.68,  55.7 ,  98.2 , 109.96,  35.71,  87.85,  30.22],
       [  0.97,  41.53,  57.21,  99.19, 111.47,  36.27,  89.11,  30.91]])

In [49]:
fall = np.greater(stocks[0], stocks[1])
fall

array([ True, False, False, False, False, False, False, False])

In [50]:
sap[fall]

array(['MMM'], dtype='<U4')

In [51]:
stocks[1, 0] = np.nan
np.isnan(stocks)

array([[False, False, False, False, False, False, False, False],
       [ True, False, False, False, False, False, False, False]])

In [53]:
stocks[np.isnan(stocks)] = 0
stocks

array([[140.49,  40.68,  55.7 ,  98.2 , 109.96,  35.71,  87.85,  30.22],
       [  0.  ,  41.53,  57.21,  99.19, 111.47,  36.27,  89.11,  30.91]])

## Understanding Conditional Functions

In [55]:
changes = np.where(np.abs(stocks[1] - stocks[0]) > 1.00,
                   stocks[1] - stocks[0], 0)
changes


array([-140.49,    0.  ,    1.51,    0.  ,    1.51,    0.  ,    1.26,
          0.  ])

In [56]:
sap[np.nonzero(changes)]

array(['MMM', 'ABBV', 'ACE', 'ADBE'], dtype='<U4')

In [57]:
sap[np.abs(stocks[1] - stocks[0]) > 1.00]

array(['MMM', 'ABBV', 'ACE', 'ADBE'], dtype='<U4')

## Aggregating and Ordering Arrays

In [58]:
 sap[          np.abs(stocks[0] - stocks[1])
       > np.mean(np.abs(stocks[0] - stocks[1]))]

array(['MMM'], dtype='<U4')

## Treating Arrays as Sets

In [59]:
dna = "AGTCCGCGAATACAGGCTCGGT" 
dna_as_array = np.array(list(dna))

In [60]:
np.unique(dna_as_array)

array(['A', 'C', 'G', 'T'], dtype='<U1')

In [61]:
np.in1d(["MSFT", "MMM", "AAPL"], sap)

array([False,  True, False])